# Generated by Django 4.1.13 on 2024-08-30 17:35

from django.db import migrations, models
import django_db_cascade.deletions
import django_db_cascade.fields


class Migration(migrations.Migration):

    dependencies = [
        ("crapi", "0003_alter_appliedcoupon_id_alter_mechanic_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("inprogress", "In Progress"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ServiceComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("created_on", models.DateTimeField()),
                (
                    "service_request",
                    django_db_cascade.fields.ForeignKey(
                        on_delete=django_db_cascade.deletions.DB_CASCADE,
                        to="crapi.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "service_comment",
            },
        ),
    ]
